- name: Power on VM "{{ item }}" and wait for ip
  vmware_guest:
    hostname: "{{ vcenter_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vcenter_folder }}"
    name: "{{ item }}"
    state: poweredon
    state_change_timeout: 60
    wait_for_ip_address: true
  when: no_wait is undefined

- name: Power on VM "{{ item }}"
  vmware_guest:
    hostname: "{{ vcenter_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    folder: "{{ vcenter_folder }}"
    name: "{{ item }}"
    state: poweredon
    state_change_timeout: 60
  when: no_wait is defined
