- name: Shutdown VM "{{ item }}"
  vmware_guest:
    hostname: "{{ vcenter_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ item }}"
    state: shutdownguest
    state_change_timeout: 180
  ignore_errors: yes
  when: 
    - hard_power_off is undefined
    - ' "rhcos" not in item '

- name: Ensure VM "{{ item }}" is powered off
  vmware_guest:
    hostname: "{{ vcenter_url }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ item }}"
    state: poweredoff
    state_change_timeout: 60
    when:
      - ' "rhcos" not in item '
